D3ltr vlad
UserCommon/webui-project pull request #1
Opened 2023-11-30 16:30 UTC by d3ltr

2023-11-30 16:43 UTC, UserCommon requested changes
![photo_2023-11-30_14-19-14](https://github.com/UserCommon/webui-project/assets/52636922/3c9c3ccd-5420-4349-ad0e-8324f04fa24a)

2023-11-30 16:43 UTC, UserCommon commented on d3ltr.html
Перенеси в соответствующий .svelte файл

2023-11-30 16:43 UTC, UserCommon commented on cssd.css
желательно юзать tailwindcss, но да ладно

2023-11-30 16:57 UTC, d3ltr commented on d3ltr.html
![image](https://github.com/UserCommon/webui-project/assets/113023856/f577da2a-6e56-4fdd-9a04-0678e1a67dcc)

2023-11-30 16:59 UTC, demrert commented on d3ltr.html
![image](https://github.com/UserCommon/webui-project/assets/113023856/14f1cb1d-690a-46aa-ab57-2a0511ca5908)

2023-11-30 17:00 UTC, d3ltr commented
чилееен

2023-12-04 14:14 UTC, UserCommon commented
ужас....

2023-12-04 14:15 UTC, UserCommon commented
ужас

2023-12-04 14:15 UTC, closed without merging