Team
UserCommon/webui-project pull request #8
Opened 2023-12-18 20:49 UTC by Kvesten

Сделал пункт team, жду разноса

2023-12-18 22:32 UTC, UserCommon commented
![изображение](https://github.com/UserCommon/webui-project/assets/52636922/62badabd-a4b4-45f6-9bd9-023272226028)
Сломанное отображение как минимум

2023-12-18 22:42 UTC, UserCommon requested changes
вердикт: переделывай

2023-12-18 22:42 UTC, UserCommon commented on src/lib/components/Team.svelte
> +    margin-left: 300px;
1) использование css вместо tailwind(padding, margin в tailwind == m-[v], p-[v])
2) задаёшь через пиксели отступы? нужно ли пояснять почему это ужасно? 
    1) ЭТО НЕ ЦЕНТРОВКА
    2) На разных размерах это смотрится по разному
 
 открывай мануал tailwindcss и ищи mx-auto

2023-12-18 22:42 UTC, UserCommon commented on src/lib/components/Team.svelte
> +  <div class="grid grid-cols-3 my-grid">
нет адаптивности(https://tailwindcss.com/docs/responsive-design). Смотри картинку, на маленькой ширине grid-cols-2.

2023-12-18 22:42 UTC, UserCommon commented on src/lib/components/Team.svelte
> +    <div class="card">
Задание со звёздочкой. можно запихнуть div.card в отдельный компонент

2023-12-18 22:42 UTC, UserCommon commented on src/lib/components/Team.svelte
> +  <div class="grid grid-cols-3 my-grid">
Ещё между квадратиками гридбокса можно задавать параметр gap-[v] - отступ между клетками

2023-12-18 22:42 UTC, UserCommon commented on src/lib/components/Team.svelte
> +<main>
ЭТО НЕ `<main>`, А `<section>`

2023-12-18 22:42 UTC, UserCommon commented on src/lib/components/Team.svelte
> +    margin-left: 300px;
https://tailwindcss.com/docs/margin

2023-12-22 00:48 UTC, Kvesten commented
Вроде поправил, жду правок =)

2023-12-22 10:10 UTC, UserCommon requested changes
ещё немного

2023-12-22 10:10 UTC, UserCommon commented on src/lib/components/Team.svelte
> +        <p class="card_desc">
Сделай, чтобы текст этого тега на телефонах был меньше, а на компьютере такое же (прописать классы text-xxx, lg:text-XXX, по принципу  mobile first)

2023-12-22 10:10 UTC, UserCommon commented on src/lib/components/Team.svelte
в оригинальной вёрстке есть кнопка ВСЯ КОМАНДА. сделай её

2023-12-22 10:17 UTC, UserCommon commented
ну и ещё там текст на карточках подгони под картинку

2023-12-22 10:44 UTC, UserCommon commented
ещё вот это добавить сверху
![изображение](https://github.com/UserCommon/webui-project/assets/52636922/00d4f993-2a7f-4b1c-bf36-91fa2c681afe)

2023-12-23 19:56 UTC, Kvesten commented
Ну вроде

2023-12-23 21:21 UTC, UserCommon requested changes

2023-12-23 21:21 UTC, UserCommon commented on src/lib/components/Team.svelte
> +      class="grid grid-cols-1 lg:grid-cols-3 gap-x-4 gap-y-10 w-8/12 text-left justify-items-center m15"
mt-15 -> mx-auto

2023-12-23 21:21 UTC, UserCommon commented on src/lib/components/Team.svelte
> +    <div class="text-left test mini-title">
broken mobile view

2023-12-23 23:25 UTC, UserCommon approved these changes
lgfm

2023-12-23 23:25 UTC, merged